# -*- coding: utf-8 -*-
"""openai_llm_api_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y9fgOae13aPp29lp_R-Km6zwInpOnxOb
"""

#3.1 ACCESSING OPENAI LLM

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U openai

import os

import os
from openai import OpenAI



"""trying different models"""

from openai import OpenAI

client = OpenAI()

response = client.responses.create(
    model= "gpt-3.5-turbo-0125",
    input="Tell me a three sentence bedtime story about a unicorn"
)

print(response.output[0].content[0].text)

from openai import OpenAI

client = OpenAI()

response = client.responses.create(
    model= "gpt-4.1-2025-04-14",
    input="Why sky is blue?"
)

print(response.output[0].content[0].text)

"""chat completion"""

from openai import OpenAI

client = OpenAI()

completion = client.chat.completions.create(
    model= "gpt-3.5-turbo-0125",
    messages=[
        {
            "role": "system","content": "you are helpful assistant"
        },
        {
            "role": "user","content": "who won world series in 2020?"
        }
    ]
)